"""added field created_by in batch

Revision ID: 61eca10dee1a
Revises: 2276d390f9f7
Create Date: 2026-04-22 17:24:56.020749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61eca10dee1a'
down_revision: Union[str, Sequence[str], None] = '2276d390f9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batches', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_column('batches', 'created_by')
    # ### end Alembic commands ###
